hibernate.connection.url = jdbc:mysql://localhost:3306/manytomany
hibernate.connection.username = root
hibernate.connection.password = Pravi_19k
hibernate.hbm2ddl.auto = create
hibernate.show_sql = true
hibernate.format_sql = true
hibernate.highlight_sql = true
